### ISSUE TITLE
Error when using --config option  A valid configuration file is required.

### ISSUE THREAD

**Issue by itzikb-redhat** [bregman-arie/jcli#1]
When running 
# jcli job --config /etc/jcli/myconf list 

I get: 
Traceback (most recent call last):
  File "/bin/jcli", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/jcli/cmd.py", line 32, in main
    run_config = config.read(args.config)
  File "/usr/lib/python2.7/site-packages/jcli/config.py", line 50, in read
    "\n{0} is not a valid configuration file".format(config_file))
jcli.errors.JcliException: A valid configuration file is required.
/etc/jcli/config.ini is not a valid configuration file
myconf

[jenkins]
user=myuser
password=mypassword
url=http://127.0.0.1:8080

**Comment by bregman-arie** [comment]
Couldn't reproduce. Ping when you are available, I'll try to help by connecting remotely.

**Comment by bregman-arie** [comment]
@itzikb-redhat can you try to run it on anther server?

**Comment by itzikb-redhat** [comment]
No problem with CentOS 7.2

**Comment by bregman-arie** [comment]
So it's an issue with your original environment?

**Comment by itzikb-redhat** [comment]
Seems so
