### ISSUE TITLE
ability to use multiple jenkins servers

### ISSUE THREAD

**Issue by ssbarnea** [bregman-arie/jcli#13]
At this moment the tool can use only one Jenkins server and we need the ability to refer to multiple jenkins masters. 

We can use multiple ini sections and use the "jenkins" one as the default one.

Now what I do not yet know if what command line argument would be the best for telling the tool which master to use.

I propose `-s[default]` and `--server [default]` for that but before making any PR, I would like to hear your view.

**Comment by bregman-arie** [comment]
I like the idea. My view on how it should work:

In the .ini file, you'll have multiple [jenkins/<name>] sections and by default it would either use the first one in the list or the one that includes the option 'default=yes'.
To use a specific server, you'll need to specify the name of the server as it appears in the section ( [jenkins/<name>] ).

For example:

[jenkins/a]
...
[jenkins/b]
default=yes
...
[jenkins/c]

In this case it would connect jenkins/b by default, but I can also specify -s c or -s a

**Comment by ssbarnea** [comment]
I am already using the current version in "production" ;)

I used this approach in order not ti change current behaviour and to keep it compatible with jenkins-job-builder. The user needs to specify the full section name if they want to use something else then default one. It is intuitive

**Comment by bregman-arie** [comment]
"I am already using the current version in "production" ;)" - which version? I think I lost you.

**Comment by ssbarnea** [comment]
Oops, my mistake, I imagined that I already pushed the patch for it. Before I push a patch addressing this lets first have this feature implemented in jjb. 

The CR doing it it is pending review at https://review.openstack.org/#/c/469146/ -- once we get in, we will be able to implement it the same way.
